import { StyleSheet } from "react-native";
import type { ThemeColors } from "./themes";

export function createAppStyles(c: ThemeColors) {
  return StyleSheet.create({
    screen: { flex: 1, backgroundColor: c.bg },
    loginScreen: { flex: 1, backgroundColor: c.loginBg },
    appContainer: { flex: 1, position: "relative" },
    content: { padding: 16, gap: 14, paddingBottom: 28 },
    appHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 12,
      backgroundColor: c.surface,
      borderBottomWidth: 1,
      borderBottomColor: c.line,
    },
    headerLeft: { flex: 1, minWidth: 0, flexDirection: "row", alignItems: "center", gap: 12 },
    headerActions: { flexDirection: "row", alignItems: "center", gap: 8, position: "relative" },
    logout: {
      width: 32,
      height: 32,
      borderRadius: 7,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: c.primaryLight,
      borderWidth: 1,
      borderColor: c.primaryBorder,
    },
    syncBtn: {
      width: 32,
      height: 32,
      borderRadius: 7,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: c.primaryLight,
      borderWidth: 1,
      borderColor: c.primaryBorder,
    },
    syncBtnActive: { backgroundColor: c.accentBg, borderColor: c.gold },
    syncBadge: {
      position: "absolute",
      top: 5,
      right: 5,
      minWidth: 16,
      height: 16,
      borderRadius: 8,
      backgroundColor: c.gold,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 3,
    },
    syncBadgeText: { color: c.text, fontSize: 9, fontWeight: "900" },
    syncTooltip: {
      position: "absolute",
      bottom: 50,
      right: 0,
      backgroundColor: c.navy,
      borderRadius: 7,
      paddingHorizontal: 10,
      paddingVertical: 7,
      zIndex: 99,
      shadowColor: "#000",
      shadowOpacity: 0.28,
      shadowRadius: 10,
      elevation: 8,
      minWidth: 200,
    },
    syncTooltipText: { color: c.onPrimary, fontSize: 12, fontWeight: "700", textAlign: "center" },
    syncIcon: { width: 22, height: 22, position: "relative", alignItems: "center", justifyContent: "center" },
    syncArcTop: {
      position: "absolute",
      width: 16,
      height: 16,
      borderRadius: 8,
      borderWidth: 2.5,
      borderColor: c.blue,
      borderBottomColor: "transparent",
      borderLeftColor: "transparent",
      top: 1,
      left: 1,
    },
    syncArcBottom: {
      position: "absolute",
      width: 16,
      height: 16,
      borderRadius: 8,
      borderWidth: 2.5,
      borderColor: c.blue,
      borderTopColor: "transparent",
      borderRightColor: "transparent",
      bottom: 1,
      right: 1,
    },
    syncArrowTop: {
      position: "absolute",
      top: 0,
      right: 2,
      width: 0,
      height: 0,
      borderTopWidth: 5,
      borderBottomWidth: 5,
      borderLeftWidth: 5,
      borderTopColor: "transparent",
      borderBottomColor: "transparent",
      borderLeftColor: c.blue,
      transform: [{ rotate: "-45deg" }],
    },
    syncArrowBottom: {
      position: "absolute",
      bottom: 0,
      left: 2,
      width: 0,
      height: 0,
      borderTopWidth: 5,
      borderBottomWidth: 5,
      borderLeftWidth: 5,
      borderTopColor: "transparent",
      borderBottomColor: "transparent",
      borderLeftColor: c.blue,
      transform: [{ rotate: "135deg" }],
    },
    menuToggle: {
      width: 44,
      height: 44,
      borderRadius: 7,
      alignItems: "center",
      justifyContent: "center",
      gap: 5,
      backgroundColor: c.primaryLight,
      borderWidth: 1,
      borderColor: c.primaryBorder,
    },
    menuBar: { width: 22, height: 3, borderRadius: 3, backgroundColor: c.blue },
    menuOverlay: { position: "absolute", top: 0, left: 0, right: 0, bottom: 0, backgroundColor: "rgba(0,0,0,0.35)", zIndex: 10 },
    menuWrap: {
      position: "absolute",
      top: 68,
      left: 0,
      right: 0,
      zIndex: 11,
      gap: 4,
      padding: 12,
      backgroundColor: c.surface,
      borderBottomWidth: 1,
      borderBottomColor: c.line,
      shadowColor: "#000",
      shadowOpacity: 0.18,
      shadowRadius: 18,
      elevation: 12,
    },
    menuItem: { minHeight: 44, justifyContent: "center", borderRadius: 7, paddingHorizontal: 14, backgroundColor: c.accentBg },
    menuItemActive: { backgroundColor: c.blue },
    menuText: { color: c.muted, fontWeight: "800", fontSize: 13 },
    menuTextActive: { color: c.onPrimary },
    submenuWrap: { gap: 5, marginLeft: 12, marginTop: 5, marginBottom: 3, paddingLeft: 10, borderLeftWidth: 2, borderLeftColor: c.primaryBorder },
    submenuItem: { minHeight: 38, justifyContent: "center", borderRadius: 7, paddingHorizontal: 12, backgroundColor: c.bg },
    submenuItemActive: { backgroundColor: c.primaryLight, borderWidth: 1, borderColor: c.primaryBorder },
    submenuText: { color: c.muted, fontWeight: "800", fontSize: 12 },
    submenuTextActive: { color: c.blue },
    loginContent: { flexGrow: 1, padding: 22, justifyContent: "center", gap: 22 },
    loginCircleOne: { position: "absolute", width: 260, height: 260, borderRadius: 130, backgroundColor: `${c.gold}3D`, top: -86, right: -82 },
    loginCircleTwo: { position: "absolute", width: 220, height: 220, borderRadius: 110, backgroundColor: `${c.green}2E`, bottom: -72, left: -72 },
    mobileHero: { gap: 10, alignItems: "flex-start" },
    mobileLogo: {
      width: 86,
      height: 86,
      borderRadius: 24,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: c.surface,
      borderWidth: 3,
      borderColor: c.gold,
      shadowColor: "#000",
      shadowOpacity: 0.25,
      shadowRadius: 18,
      elevation: 8,
    },
    mobileLogoText: { color: c.blue, fontSize: 30, fontWeight: "900" },
    mobileKicker: {
      overflow: "hidden",
      borderRadius: 20,
      paddingHorizontal: 12,
      paddingVertical: 6,
      color: c.navy,
      backgroundColor: c.gold,
      fontSize: 12,
      fontWeight: "900",
      textTransform: "uppercase",
    },
    mobileTitle: { color: c.onPrimary, fontSize: 42, lineHeight: 44, fontWeight: "900" },
    mobileSubtitle: { color: "rgba(255,255,255,0.82)", fontSize: 16, lineHeight: 24 },
    loginCard: {
      gap: 16,
      padding: 20,
      borderRadius: 8,
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.line,
      shadowColor: "#000",
      shadowOpacity: 0.22,
      shadowRadius: 28,
      elevation: 10,
    },
    loginCardTitle: { color: c.navy, fontSize: 26, fontWeight: "900" },
    loginCardText: { marginTop: 5, color: c.muted, lineHeight: 21 },
    inputGroup: { gap: 7 },
    inputLabel: { color: c.text, fontSize: 13, fontWeight: "800" },
    loginInput: {
      height: 54,
      borderWidth: 1,
      borderColor: c.line,
      borderRadius: 7,
      paddingHorizontal: 14,
      backgroundColor: c.bg,
      color: c.text,
      fontSize: 16,
    },
    loginPrimary: {
      minHeight: 56,
      borderRadius: 7,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: c.blue,
      shadowColor: c.blue,
      shadowOpacity: 0.26,
      shadowRadius: 16,
      elevation: 5,
    },
    loginBadges: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
    loginBadge: {
      overflow: "hidden",
      borderRadius: 20,
      paddingHorizontal: 10,
      paddingVertical: 6,
      color: c.blue,
      backgroundColor: c.primaryLight,
      fontSize: 12,
      fontWeight: "800",
    },
    splash: { flex: 1, alignItems: "center", justifyContent: "center", gap: 12, backgroundColor: c.bg },
    splashCompact: { flex: 0, paddingVertical: 12 },
    spinnerStage: { width: 188, height: 188, alignItems: "center", justifyContent: "center" },
    spinnerStageCompact: { width: 96, height: 96 },
    spinnerOrbit: {
      position: "absolute",
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      borderRadius: 94,
      borderWidth: 8,
      borderColor: c.gold,
      borderTopColor: "transparent",
      shadowColor: "#000",
      shadowOpacity: 0.22,
      shadowRadius: 22,
      elevation: 8,
    },
    spinnerOrbitCompact: { borderRadius: 48, borderWidth: 5 },
    spinnerInnerOrbit: {
      position: "absolute",
      width: 82,
      height: 82,
      borderRadius: 41,
      borderWidth: 5,
      borderColor: c.blue,
      borderRightColor: "transparent",
    },
    spinnerInnerOrbitCompact: { width: 42, height: 42, borderRadius: 21, borderWidth: 3 },
    spinnerLogoDisk: {
      width: 72,
      height: 72,
      borderRadius: 36,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: c.surface,
    },
    spinnerLogoDiskCompact: { width: 38, height: 38, borderRadius: 19 },
    spinnerLogoText: { color: c.blue, fontSize: 24, fontWeight: "900" },
    spinnerLogoTextCompact: { fontSize: 13 },
    spinnerArrow: {
      position: "absolute",
      width: 0,
      height: 0,
      borderTopWidth: 12,
      borderBottomWidth: 12,
      borderLeftWidth: 24,
      borderTopColor: "transparent",
      borderBottomColor: "transparent",
      borderLeftColor: c.gold,
    },
    spinnerArrowCompact: { borderTopWidth: 7, borderBottomWidth: 7, borderLeftWidth: 14 },
    spinnerArrowOne: { left: 24, top: 20, transform: [{ rotate: "138deg" }] },
    spinnerArrowTwo: { left: 14, bottom: 32, transform: [{ rotate: "14deg" }] },
    spinnerArrowThree: { right: 8, top: 86 },
    spinnerArrowOneCompact: { left: 12, top: 10 },
    spinnerArrowTwoCompact: { left: 7, bottom: 16 },
    spinnerArrowThreeCompact: { right: 4, top: 42 },
    brand: { fontSize: 24, fontWeight: "900", color: c.blue },
    muted: { color: c.muted },
    sectionTitle: { gap: 4 },
    pageTitle: { fontSize: 27, fontWeight: "900", color: c.text },
    card: { backgroundColor: c.surface, borderRadius: 8, padding: 16, gap: 12, borderWidth: 1, borderColor: c.line },
    title: { fontSize: 18, fontWeight: "800", color: c.text },
    formStack: { gap: 12 },
    field: { gap: 7 },
    input: {
      minHeight: 46,
      borderWidth: 1,
      borderColor: c.line,
      borderRadius: 7,
      paddingHorizontal: 12,
      paddingVertical: 10,
      backgroundColor: c.surface,
      color: c.text,
    },
    inputMultiline: { minHeight: 92 },
    choiceWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
    choiceChip: {
      maxWidth: "100%",
      minHeight: 36,
      justifyContent: "center",
      borderRadius: 18,
      borderWidth: 1,
      borderColor: c.line,
      paddingHorizontal: 12,
      paddingVertical: 7,
      backgroundColor: c.bg,
    },
    choiceChipActive: { borderColor: c.blue, backgroundColor: c.blue },
    choiceText: { maxWidth: 220, color: c.muted, fontSize: 12, fontWeight: "800" },
    choiceTextActive: { color: c.onPrimary },
    checkRow: {
      minHeight: 36,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      borderWidth: 1,
      borderColor: c.line,
      borderRadius: 7,
      paddingHorizontal: 9,
      backgroundColor: c.bg,
    },
    checkBox: { width: 18, height: 18, borderRadius: 5, borderWidth: 1.5, borderColor: c.primaryBorder, backgroundColor: c.surface, alignItems: "center", justifyContent: "center" },
    checkBoxActive: { borderColor: c.blue, backgroundColor: c.blue },
    checkMark: { width: 6, height: 11, borderBottomWidth: 2, borderRightWidth: 2, borderColor: c.onPrimary, transform: [{ rotate: "45deg" }], marginTop: -2 },
    checkText: { color: c.text, fontWeight: "600", fontSize: 13 },
    primary: { minHeight: 46, borderRadius: 7, alignItems: "center", justifyContent: "center", backgroundColor: c.blue },
    primaryText: { color: c.onPrimary, fontWeight: "800" },
    secondary: { minHeight: 46, borderRadius: 7, alignItems: "center", justifyContent: "center", backgroundColor: c.gold },
    secondaryText: { color: c.text, fontWeight: "800" },
    actionRow: { borderBottomWidth: 1, borderBottomColor: c.line, paddingBottom: 10, gap: 8 },
    actionRowButtons: { flexDirection: "row", gap: 8 },
    actionButton: { flex: 1, minHeight: 40 },
    iconActions: { flexDirection: "row", gap: 7, alignItems: "center" },
    actionIconButton: {
      width: 36,
      height: 36,
      borderRadius: 7,
      borderWidth: 1,
      borderColor: c.primaryBorder,
      backgroundColor: c.primaryLight,
      alignItems: "center",
      justifyContent: "center",
    },
    actionIconButtonDanger: { borderColor: `${c.red}55`, backgroundColor: "#fee2e2" },
    editIcon: { width: 18, height: 18, position: "relative" },
    editIconBody: { position: "absolute", left: 6, top: 1, width: 5, height: 16, borderRadius: 3, backgroundColor: c.blue, transform: [{ rotate: "45deg" }] },
    editIconTip: { position: "absolute", right: 1, bottom: 1, width: 0, height: 0, borderLeftWidth: 4, borderRightWidth: 4, borderTopWidth: 6, borderLeftColor: "transparent", borderRightColor: "transparent", borderTopColor: c.blue, transform: [{ rotate: "45deg" }] },
    deleteIcon: { width: 18, height: 18, position: "relative", alignItems: "center" },
    deleteIconLid: { position: "absolute", top: 2, width: 14, height: 2, borderRadius: 2, backgroundColor: c.blue },
    deleteIconCan: { position: "absolute", top: 6, width: 13, height: 11, borderWidth: 2, borderTopWidth: 0, borderColor: c.blue, borderBottomLeftRadius: 3, borderBottomRightRadius: 3, flexDirection: "row", justifyContent: "center", gap: 2, paddingTop: 2 },
    deleteIconLine: { width: 2, height: 7, borderRadius: 2, backgroundColor: c.blue },
    iconDanger: { backgroundColor: c.red },
    iconDangerBorder: { borderColor: c.red, borderTopColor: c.red },
    toast: {
      position: "absolute",
      left: 16,
      bottom: 18,
      maxWidth: "86%",
      borderRadius: 8,
      borderWidth: 1,
      borderColor: `${c.green}55`,
      backgroundColor: "#dcfce7",
      paddingHorizontal: 14,
      paddingVertical: 11,
      shadowColor: "#000",
      shadowOpacity: 0.18,
      shadowRadius: 16,
      elevation: 20,
      zIndex: 9999,
    },
    toastText: { color: "#14532d", fontSize: 13, fontWeight: "800" },
    logoutIcon: { position: "relative", width: 25, height: 25 },
    logoutDoor: {
      position: "absolute",
      left: 2,
      top: 3,
      width: 10,
      height: 19,
      borderWidth: 2,
      borderRightWidth: 0,
      borderColor: c.blue,
      borderRadius: 2,
    },
    logoutArrowStem: { position: "absolute", left: 9, top: 12, width: 13, height: 2, borderRadius: 2, backgroundColor: c.blue },
    logoutArrowHead: {
      position: "absolute",
      right: 2,
      top: 8,
      width: 8,
      height: 8,
      borderTopWidth: 2,
      borderRightWidth: 2,
      borderColor: c.blue,
      transform: [{ rotate: "45deg" }],
    },
    stats: { flexDirection: "row", gap: 10 },
    stat: { flex: 1, backgroundColor: c.surface, borderRadius: 8, padding: 12, borderWidth: 1, borderColor: c.line },
    statValue: { marginTop: 6, fontSize: 16, fontWeight: "900", color: c.text },
    row: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 12,
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: c.line,
    },
    rowText: { flex: 1, minWidth: 0 },
    rowTitle: { color: c.text, fontWeight: "800" },
    rowSubtitle: { marginTop: 3, color: c.muted, fontSize: 12 },
    empty: { color: c.muted, paddingVertical: 10 },
    pill: {
      maxWidth: 124,
      overflow: "hidden",
      borderRadius: 20,
      paddingHorizontal: 8,
      paddingVertical: 4,
      backgroundColor: c.primaryLight,
      color: c.blue,
      fontWeight: "800",
      fontSize: 12,
    },
  });
}

export type AppStyles = ReturnType<typeof createAppStyles>;
